AllCops:
  TargetRubyVersion: 3.2

Metrics/BlockLength:
  ExcludedMethods: ["describe", "context"]

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
