AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Metrics/BlockLength:
  AllowedMethods: ["describe", "context"]

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
